# Generated by Django 3.2.5 on 2021-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0002_delete_loadbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=256, null=True)),
                ('barcode', models.CharField(default=None, max_length=64, null=True)),
                ('location', models.CharField(default=None, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
